### ISSUE TITLE
Arrangement of the files

### ISSUE THREAD

**Issue by Debaditya-Som** [Debaditya-Som/Data-Visualization-in-Python#14]
Arranging of the various .py files into one single folder for easy accessibility and clear visualization of the repository

**Comment by joshijoe05** [comment]
Hello, can I work on this issue?

**Comment by Debaditya-Som** [comment]
> Hello, can I work on this issue?

Yes absolutely, just create a folder named: "Visualization codes"  (or something like that) and then add all the files in it

**Comment by dynamicdhxx** [comment]
Heyy!
I would like to arrange the .py files. Kindly assign the issue to me 😊.

**Comment by dynamicdhxx** [comment]
could you assign the issue please 😊.

**Comment by Debaditya-Som** [comment]
@dynamicdhxx , I have already assigned to @joshijoe05 as he has asked first, you may contribute to the other issues or create an issue on your own.
Although I am assigning both of you to work on this repo, you still can work on the other issues 😊
