### ISSUE TITLE
Documentation of CONTRIBUTIONS.md

### ISSUE THREAD

**Issue by Debaditya-Som** [Debaditya-Som/Data-Visualization-in-Python#16]
Documentation of Contribution Guidelines  under a file named CONTRIBUTIONS.md

**Comment by dynamicdhxx** [comment]
Heyy!
Could i work on this issue instead ?🙂.

**Comment by Debaditya-Som** [comment]
@dynamicdhxx yess surely , add a CONTRIBUTIONS.md file

**Comment by Debaditya-Som** [comment]
> hey! need help on the documentation stuff?

Yes absolutely, could you help out for the documentation stuffs?

**Comment by thekatiedee** [comment]
i'd love to. actually specifically looking for projects where i can help out of docs. could you please give me a sense of where you'd like me to start?

**Comment by dynamicdhxx** [comment]
could I get a brief of what kind of documentation would you require ? It would provide me a headstart

**Comment by Debaditya-Som** [comment]
> could I get a brief of what kind of documentation would you require ? It would provide me a headstart

I've assigned you with the contribution guidelines documentation, like basically how a person would contribute to this repository, giving a short description of the folders and the git commands

**Comment by Debaditya-Som** [comment]
> i'd love to. actually specifically looking for projects where i can help out on docs. could you please give me a sense of where you'd like me to start?

This is actually a repository based on python, but in order to promote and grow the open source contribution, we've also kept the provision of non-code contributions like documentation, ui/ux improvement, etc. 

You can start anywhere in this repo, where you feel comfortable and feel that documentation is required or needs to be modified. For example Reame.md file or you may even create a new documentations 😊
