### ISSUE TITLE
Documentation of CODE OF CONDUCT

### ISSUE THREAD

**Issue by Debaditya-Som** [Debaditya-Som/Data-Visualization-in-Python#17]
The documentation of our project's code of conduct can be further improved to provide clear guidelines and expectations for contributors. A well-documented code of conduct is essential to maintain a positive and inclusive community within our project.

Our Code of Conduct should adhere to the code of conduct of Hacktoberfest 2023

**Comment by Madhvik007** [comment]
I can do this

**Comment by Debaditya-Som** [comment]
@Madhvik007 Yes surely, just stick o the code of conduct of Hacktoberfest 2023, and refer to their website for details

**Comment by Debaditya-Som** [comment]
Yes its good but it seems to be generated by chatGPT, which is fine but I would advise you can refer to [Hacktoberfest Official Site](https://hacktoberfest.com/participation) for making the documentation more authentic and for better understanding of the code of conduct.

**Comment by sagnik-p** [comment]
my i work on this?

**Comment by Debaditya-Som** [comment]
@sagnik-p Yes surely
Just make sure it is not generated from prompts like chatGPT or such and stick to the code of conduct of Hacktoberfest 2023, and refer to their website for details

**Comment by sagnik-p** [comment]
I have submitted the PR ( #48 )
Please check it once and tell me if some changes/addition is necessary
I have not used any generative AI and the entire thing is hand typed by me
Thanks
