### ISSUE TITLE
[UI/UX] Adjusting the size of the Data Visualization image 

### ISSUE THREAD

**Issue by Debaditya-Som** [Debaditya-Som/Data-Visualization-in-Python#20]
The image in the READEME.md file for data visualization seems too big for the markdown file.

Suggested solution:

Adjust the size of the image and make it visually appealing for the users/ contributors of this repository

**Comment by nrhitik** [comment]
I would like to work on this issue. Could you please assign me this issue.

**Comment by Debaditya-Som** [comment]
> I would like to work on this issue. Could you please assign me this issue.

Yes surely, you may work on this issue
