### ISSUE TITLE
[FEATURE REQUEST] Addition of contributor's profile image in readme.md

### ISSUE THREAD

**Issue by Debaditya-Som** [Debaditya-Som/Data-Visualization-in-Python#22]
Addition of the contributor's profile images in the README.md file :
Like this:
![image](https://github.com/Debaditya-Som/Data-Visualization-in-Python/assets/121785700/1a0b79ab-4481-44c6-aa8a-b16825204e35)

Generate an image of contributors to keep README.md in sync.

**Comment by Kunal0127** [comment]
its look like complete but if not then i would like to make this change.
can you assign this to me?

**Comment by Debaditya-Som** [comment]
> its look like complete but if not then i would like to make this change.
> can you assign this to me?

Yes surely if you can modify it then go ahead :)
